lanuage: ruby
script: bundle exec rake --rakefile $PWD/Rakefile spec SPEC_OPTS='--format documentation'
notifications:
  email: false
rvm:
  - 1.8.7
  - 1.9.3
  - 2.0.0
env:
  matrix:
    - PUPPET_GEM_VERSION="~> 2.7.0"
    - PUPPET_GEM_VERSION="~> 3.0"
